[theme]
primaryColor = "#D87D9C"
backgroundColor = "#1C1C24"
secondaryBackgroundColor = "#2B2B33"
textColor = "#F4F4F4"
font = "sans serif"

[server]
headless = true
enableCORS = false
enableXsrfProtection = false
